---
# Origin from: https://nsirap.com/posts/048-ansible-install-docker-and-docker-compose/
  - name: Install dependencies
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - software-properties-common
      state: latest
      update_cache: yes

  - name: Add GPG key
    apt_key:
      url: "https://download.docker.com/linux/{{ 'debian' if ansible_distribution | lower == 'debian' else 'ubuntu' }}/gpg"
      state: present

  - name: Add Docker repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ 'debian' if ansible_distribution | lower == 'debian' else 'ubuntu' }} {{ ansible_distribution_release }} stable"
      state: present

  - name: Install Docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: latest
      update_cache: yes

  - name: Add users to docker group
    user:
      name: '{{ item }}'
      groups: docker
      append: yes
    loop:
      - "{{ ansible_user }}"

